name       : ptlib
version    : 2.10.11
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/ptlib/2.10/ptlib-2.10.11.tar.xz : 3a17f01d66301663f76130b425d93c2730f2a33df666982165166ff4653dc2c9
license    : MPL-1
component  : programming
summary    : PTLib (Portable Tools Library) is a library for I/O portability, multi-threading
    portability, and more.
description: |
    PTLib (Portable Tools Library) is a library for I/O portability, multi-threading portability, aid in producing unix daemons and NT services portably and all sorts of internet protocols
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(expat)
    - pkgconfig(krb5)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libdv)
    - pkgconfig(libpulse)
    - pkgconfig(libraw1394)
    - pkgconfig(libsasl2)
    - pkgconfig(libv4l2)
    - pkgconfig(lua-5.1)
    - pkgconfig(openssl)
    - pkgconfig(sdl)
    - pkgconfig(sdl2)
    - bison
    - flex
setup      : |
    %configure --disable-static \
        --enable-audio \
        --enable-configfile \
        --enable-ftp \
        --enable-http \
        --enable-ipv6 \
        --enable-opal \
        --enable-oss \
        --enable-plugins \
        --enable-pulse \
        --enable-sasl \
        --enable-soap \
        --enable-socks \
        --enable-v4l \
        --enable-v4l2 \
        --enable-video \
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/libpt_s.a
